#serve-CI
name: CI

on: 
  push:
    branches:
      - dev

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd /home/${{ secrets.USERNAME }}/github/bitrxc-server
            git pull
            docker-compose --env ./deploy/environment/.env.dev down
            docker-compose --env ./deploy/environment/.env.dev up --detach --build
